# Generated by Django 5.1.2 on 2025-11-21 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkinCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Skin Category',
                'verbose_name_plural': 'Skin Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkinTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=40, unique=True)),
            ],
            options={
                'verbose_name': 'Skin Tag',
                'verbose_name_plural': 'Skin Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('type', models.CharField(choices=[('regular', 'Regular Skin'), ('hd', 'HD Skin'), ('cape', 'Cape'), ('special', 'Special / Event')], default='regular', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('image', models.ImageField(upload_to='skins/previews/')),
                ('file', models.FileField(help_text='Скін у форматі PNG', upload_to='skins/files/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skins', to='shop.skincategory')),
                ('tags', models.ManyToManyField(blank=True, to='shop.skintag')),
            ],
            options={
                'verbose_name': 'Skin',
                'verbose_name_plural': 'Skins',
                'ordering': ['-created_at'],
            },
        ),
    ]
